In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
pd.options.display.max_columns = None

In [4]:
df = pd.read_csv('../data/nova_pay_combined.csv')

In [10]:
df.head()

,transaction_id,customer_id,timestamp,home_country,source_currency,dest_currency,channel,amount_src,amount_usd,fee,exchange_rate_src_to_dest,device_id,new_device,ip_address,ip_country,location_mismatch,ip_risk_score,kyc_tier,account_age_days,device_trust_score,chargeback_history_count,risk_score_internal,txn_velocity_1h,txn_velocity_24h,corridor_risk,is_fraud
0,fee8542d-8ee6-4b0d-9671-c294dd08ed26,402cccc9-28de-45b3-9af7-cc5302aa1f93,2022-10-03 18:40:59.468549+00:00,US,USD,CAD,ATM,278.19,278.19,4.25,1.351351,9f292dcc-3297-4947-a260-6a1ef69041ff,False,221.78.171.180,US,False,0.123,standard,263,0.522,0,0.223,0,0,0.0,0
1,bfdb9fc1-27fe-4a85-b043-4d813d679259,67c2c6b3-ef0a-4777-a3f1-c84a851bb6ad,2022-10-03 20:39:38.468549+00:00,CA,CAD,MXN,web,208.51,154.29,4.24,12.758621,3a95b9f5-309f-4684-a46d-e2ff2435bf78,True,120.12.20.29,CA,False,0.569,standard,947,0.475,0,0.268,0,1,0.0,0
2,fc855034-3ea5-4993-9afa-b511d93fe5e8,6d0d9b27-fa26-45f8-93b1-2df29d182d9c,2022-10-03 23:02:43.468549+00:00,US,USD,CNY,mobile,160.33,160.33,2.70,7.142857,a4737752-9aac-43ed-9d8b-2ccdffc24052,False,223.96.181.93,US,False,0.437,enhanced,367,0.939,0,0.176,0,0,0.0,0
3,2cf8c08e-42ec-444d-a755-34b9a2a0a4ca,7bd5200c-5d19-44f0-9afe-8b339a05366b,2022-10-04 01:08:53.468549+00:00,US,USD,EUR,mobile,59.41,59.41,2.22,0.925926,6aeb85a3-5603-4221-896c-9e6882764f1a,False,186.228.15.74,US,False,0.594,standard,147,0.551,0,0.391,0,0,0.0,0
4,d907a74d-b426-438d-97eb-dbe911aca91c,70a93d26-8e3a-4179-900c-a4a7a74d08e5,2022-10-04 09:35:03.468549+00:00,US,USD,INR,mobile,200.96,200.96,3.61,83.333333,a5b9250e-dbe0-4c5f-a6e7-5492b7349402,False,11.82.47.62,US,False,0.121,enhanced,257,0.894,0,0.257,0,0,0.0,0

In [7]:
df.isnull().mean()

transaction_id               0.000000
customer_id                  0.000000
timestamp                    0.002544
home_country                 0.000000
source_currency              0.000000
dest_currency                0.000000
channel                      0.000000
amount_src                   0.000000
amount_usd                   0.026754
fee                          0.025877
exchange_rate_src_to_dest    0.000000
device_id                    0.000000
new_device                   0.000000
ip_address                   0.026754
ip_country                   0.026404
location_mismatch            0.000000
ip_risk_score                0.000000
kyc_tier                     0.026316
account_age_days             0.000000
device_trust_score           0.025877
chargeback_history_count     0.000000
risk_score_internal          0.000000
txn_velocity_1h              0.000000
txn_velocity_24h             0.000000
corridor_risk                0.000000
is_fraud                     0.000000
dtype: float64

In [8]:
df.loc[df.timestamp.isnull(), :]

,transaction_id,customer_id,timestamp,home_country,source_currency,dest_currency,channel,amount_src,amount_usd,fee,...,ip_risk_score,kyc_tier,account_age_days,device_trust_score,chargeback_history_count,risk_score_internal,txn_velocity_1h,txn_velocity_24h,corridor_risk,is_fraud
158,e6ef7b85-c19f-43fa-befa-743e37c62583,6d0d9b27-fa26-45f8-93b1-2df29d182d9c,NaN,US,USD,PHP,mobile,248.92,248.92,5.56,...,0.197,enhanced,367,0.939,0,0.176,0,0,0.10,0
160,2b64ca36-f140-4de4-9cc8-c678255402a9,d71c91b4-fee8-4104-9856-a5c6109a62e3,NaN,US,USD,CNY,web,75.44,75.44,1.31,...,0.353,standard,298,0.336,0,0.166,0,0,0.00,0
578,b371fb34-0744-4b90-b33d-237b95b0cd52,6d0d9b27-fa26-45f8-93b1-2df29d182d9c,NaN,US,USD,INR,mobile,251.95,251.95,5.68,...,0.424,enhanced,367,0.939,0,0.176,0,0,0.00,0
1003,3e96cacd-3722-469f-95c1-6dce5ba73aa6,7bd5200c-5d19-44f0-9afe-8b339a05366b,NaN,US,USD,GBP,web,51.22,51.22,1.23,...,0.569,standard,147,0.401,0,0.391,0,1,0.00,0
1325,c646535b-dd51-4d09-b155-e603bbafdc7e,70a93d26-8e3a-4179-900c-a4a7a74d08e5,NaN,US,USD,USD,mobile,9993.44,9993.44,150.77,...,0.398,enhanced,257,0.894,0,0.257,0,1,0.00,0
1501,f340c84f-8021-483c-9a7e-b1fae29a3859,6d0d9b27-fa26-45f8-93b1-2df29d182d9c,NaN,US,USD,GBP,web,165.8,165.80,3.62,...,0.337,enhanced,367,0.939,0,0.176,0,0,0.00,0
1522,fcf3662d-6acd-4303-902f-0a46cefda734,7bd5200c-5d19-44f0-9afe-8b339a05366b,NaN,US,USD,GBP,mobile,90.11,90.11,2.42,...,0.268,standard,147,0.551,0,0.391,0,0,0.00,0
1780,c99dc8d7-24b9-4527-93dc-29cb6711bbe6,7041b9c1-3719-4ca8-9a6b-811b47cea6c0,NaN,UK,GBP,PHP,web,41.1,51.37,2.13,...,0.234,standard,4,0.892,0,0.407,0,0,0.00,1
2053,bf335e6c-a6bc-4fa3-96ed-516d8d7ca793,af8ca4c4-8703-4c55-b66c-2b76cd70040d,NaN,US,USD,PHP,mobile,126.75,126.75,3.55,...,0.257,standard,1018,0.934,0,0.087,0,0,0.10,0
2112,611e6035-5389-45bd-a467-6aaf83493a0a,402cccc9-28de-45b3-9af7-cc5302aa1f93,NaN,US,USD,INR,mobile,56.95,56.95,1.78,...,0.304,standard,263,0.522,0,0.223,0,1,0.00,0
2407,ec1ddb8a-2e1c-4ebf-83b1-aba6001eeb52,7041b9c1-3719-4ca8-9a6b-811b47cea6c0,NaN,UK,GBP,GBP,mobile,120.18,150.22,2.83,...,0.084,standard,4,0.892,0,0.407,0,0,0.00,0
2895,ed69b35a-66ce-42d2-a4ff-24cfc2c2a1a4,d71c91b4-fee8-4104-9856-a5c6109a62e3,NaN,US,USD,USD,mobile,71.87,71.87,1.87,...,0.309,standard,298,0.336,0,0.166,0,0,0.00,0
2985,d0687ae7-08cb-4ff2-9955-f84680f5e219,402cccc9-28de-45b3-9af7-cc5302aa1f93,NaN,US,USD,CNY,web,56.82,56.82,2.42,...,0.440,standard,263,0.522,0,0.223,0,0,0.00,0
3655,121fb625-12fd-4f12-a077-acfe7b729817,66c71a44-d07c-4a20-a576-0a377193bf6b,NaN,US,USD,CNY,mobile,612.27,612.27,10.05,...,0.381,standard,34,0.427,0,0.068,0,1,0.00,0
3840,fb761456-429b-4525-a475-a7d82c2d4fa8,7041b9c1-3719-4ca8-9a6b-811b47cea6c0,NaN,UK,GBP,NGN,web,243.09,303.86,4.57,...,0.048,standard,4,0.892,0,0.407,0,0,0.22,0
4228,d78cd55e-a56a-4de1-a694-260673854136,7041b9c1-3719-4ca8-9a6b-811b47cea6c0,NaN,UK,GBP,INR,ATM,68.08,85.09,2.25,...,0.272,standard,4,0.892,0,0.407,0,0,0.00,0
4376,dee339a6-c2ce-4192-b7b2-78c8a41f3bb8,7041b9c1-3719-4ca8-9a6b-811b47cea6c0,NaN,UK,GBP,CAD,mobile,92.59,115.74,1.65,...,0.326,standard,4,0.892,0,0.407,0,0,0.00,0
4561,b651cb3f-a640-4ae2-9b5e-8d9f74545525,66c71a44-d07c-4a20-a576-0a377193bf6b,NaN,US,USD,EUR,ATM,104.85,104.85,2.36,...,0.296,standard,34,0.427,0,0.068,0,0,0.00,0
4920,2488b461-e9cb-4c02-b3f0-344eb43e463b,402cccc9-28de-45b3-9af7-cc5302aa1f93,NaN,US,USD,MXN,mobile,96.39,96.39,2.46,...,0.476,standard,263,0.372,0,0.223,0,0,0.20,0
5150,37eee200-4a07-44d6-aeff-43bdbf6f13c6,140d2232-ee97-4934-81aa-9e5c323d7c6f,NaN,CA,CAD,INR,mobile,190.19,140.74,3.42,...,0.402,low,824,0.607,0,0.282,0,0,0.12,0
5842,88590134-873a-419c-aa83-e9f0c009b98b,7041b9c1-3719-4ca8-9a6b-811b47cea6c0,NaN,UK,GBP,MXN,ATM,187.7,234.63,3.84,...,0.160,standard,4,0.892,0,0.407,0,0,0.00,0
6003,77997ff6-6bf9-45c6-b5a1-d9f1f56aed3f,af8ca4c4-8703-4c55-b66c-2b76cd70040d,NaN,US,USD,MXN,mobile,480.95,480.95,9.27,...,0.211,standard,1018,0.934,0,0.087,0,0,0.20,0
6073,01a8cb95-acc7-4e3a-a20d-37402fb67fd1,402cccc9-28de-45b3-9af7-cc5302aa1f93,NaN,US,USD,EUR,web,58.93,58.93,1.71,...,0.341,standard,263,0.522,0,0.223,0,0,0.00,0
6299,0e87f6f4-3976-473d-88fc-849431e40805,6d0d9b27-fa26-45f8-93b1-2df29d182d9c,NaN,US,USD,INR,mobile,75.66,75.66,2.33,...,0.397,enhanced,367,0.939,0,0.176,0,0,0.00,0
8067,1f0a4978-4773-4781-9d58-f88854939065,140d2232-ee97-4934-81aa-9e5c323d7c6f,NaN,CA,CAD,EUR,mobile,240.81,178.20,4.28,...,0.015,low,824,0.607,0,0.282,4,4,0.00,0
8416,25b44147-762e-41bb-9b44-0ee0ac72cde6,d71c91b4-fee8-4104-9856-a5c6109a62e3,NaN,US,USD,EUR,mobile,666.97,666.97,10.89,...,0.061,unknown,298,0.336,0,0.166,0,0,0.00,0
8528,f24d1daf-c61a-4cf9-a88a-c4a22516a1e4,402cccc9-28de-45b3-9af7-cc5302aa1f93,NaN,US,USD,GBP,mobile,231.11,231.11,4.41,...,0.246,standard,263,0.522,0,0.223,0,0,0.00,0
8712,21a4145e-eb69-4050-bd50-116c65643d09,6d0d9b27-fa26-45f8-93b1-2df29d182d9c,NaN,US,USD,CNY,mobile,82.14,82.14,1.57,...,0.249,enhanced,367,0.939,0,0.176,0,0,0.00,0
9550,5ec16623-1a14-4178-8601-a9eaf4bc644d,6d0d9b27-fa26-45f8-93b1-2df29d182d9c,NaN,US,USD,INR,mobile,457.78,457.78,7.43,...,0.125,enhanced,367,0.939,0,0.176,3,3,0.00,0

In [11]:
df.source_currency.value_counts()

source_currency
USD    8031
GBP    2139
CAD    1230
Name: count, dtype: int64

In [12]:
df.dest_currency.value_counts()

dest_currency
NGN    1474
USD    1328
INR    1325
CNY    1324
PHP    1314
GBP    1296
CAD    1282
EUR    1196
MXN     861
Name: count, dtype: int64

In [14]:
df.loc[(df.source_currency == "USD") & (df.dest_currency == "USD"), :].head()

,transaction_id,customer_id,timestamp,home_country,source_currency,dest_currency,channel,amount_src,amount_usd,fee,exchange_rate_src_to_dest,device_id,new_device,ip_address,ip_country,location_mismatch,ip_risk_score,kyc_tier,account_age_days,device_trust_score,chargeback_history_count,risk_score_internal,txn_velocity_1h,txn_velocity_24h,corridor_risk,is_fraud
11,43a11314-6420-4e23-b0a8-69d5f010da86,af8ca4c4-8703-4c55-b66c-2b76cd70040d,2022-10-04 22:54:28.468549+00:00,US,USD,USD,mobile,9998.43,9998.43,151.63,1.0,4bb9533a-117f-455a-9e69-a484a77a7176,False,79.129.58.248,US,False,0.254,standard,1018,0.934,0,0.087,0,0,0.0,0
25,8b701ec2-f0d3-432d-bb4b-7e1745bef34f,7bd5200c-5d19-44f0-9afe-8b339a05366b,2022-10-06 09:34:57.468549+00:00,US,USD,USD,mobile,121.06,121.06,3.04,1.0,162dcfa8-d2e4-4449-9b0d-7d56fd981991,False,155.92.229.247,US,False,0.163,standard,147,0.551,0,0.391,0,0,0.0,0
32,1823877a-cc28-4333-929a-5523a0d20120,402cccc9-28de-45b3-9af7-cc5302aa1f93,2022-10-07 08:31:21.468549+00:00,US,USD,USD,mobile,232.66,232.66,4.31,1.0,33919fa4-5dbb-41b0-a895-ec15ab2c10f1,False,62.78.115.149,US,False,0.271,standard,263,0.522,0,0.223,0,0,0.0,0
34,8fe20fa1-61c3-4eae-a3ed-160718e0b209,6d0d9b27-fa26-45f8-93b1-2df29d182d9c,2022-10-07 09:07:42.468549+00:00,US,USD,USD,mobile,61.27,61.27,1.79,1.0,3deb41ac-8c17-4c96-b1e9-24c67ea0de90,False,218.149.36.208,US,False,0.223,enhanced,367,0.939,0,0.176,0,0,0.0,0
44,f38d1c57-3dd4-433e-a3cd-c07f4ec25304,af8ca4c4-8703-4c55-b66c-2b76cd70040d,2022-10-08 08:19:24.468549+00:00,US,USD,USD,web,254.28,254.28,4.22,1.0,ff15b1b0-c6a7-4bd1-8ba7-a892d37c8d02,True,56.105.104.32,US,False,0.378,standard,1018,0.784,0,0.087,0,0,0.0,0